version: '3.9'

name : 'UASP-AKSO'

services:
  mysql_server:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password 
      MYSQL_DATABASE: mydatabase 
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mynetwork

  django_server:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - mysql_server
    environment:
      DB_HOST: localhost
      DB_NAME: Project_Jaa 
      DB_USER: root
      DB_PASSWORD: jihansql23 
    networks:
      - mynetwork

volumes:
  mysql_data:

networks:
  mynetwork:
    driver: bridge
